version: '3'
services:
  web:
    build: './web'
    container_name: web
    hostname: web
    ports:
      - 3000:3000


  rabbit:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
      - 4369:4369
      - 5671:5671
    volumes:
      - /Users/vladimirbessonov/Documents/dvolumes/rabbitmq:/var/lib/rabbitmq
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"

  rpcserver:
    build: './rpcServer'
    container_name: rpcserver
    hostname: rpcserver
    ports:
      - 3001:3000
#    links:
#      - "rabbit"
    depends_on:
      - rabbit



  rpcclient:
    build: './rpcClient'
    container_name: rpcclient
    hostname: rpcclient
    ports:
      - 3002:3000
#    links:
#      - "rabbit"
    depends_on:
      - rabbit

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
      - 8080:8080
      - 9000:9000
    volumes:
      - ./web/public:/srv/www/static
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - rpcserver
      - rpcclient
      - rabbit



